export interface Tesis
{
    id_pk?:number;
    id?:number;
    nombre_completo:string;
    nombre_completo2:string;
    rut:string;
    rut2:string;
    profesor_guia:string;
    ano_ingreso:string;
    ano_ingreso2:string;
    telefono1:string;
    telefono2:string;
    carrera:string;
    tipo:string;
    nombre_vinculacion:string;
    tipo_vinculacion:string;
    nombre_tesis:string;
    area_tesis:string;
    descripcion:string;
    objetivos:string;
    contribucion:string;
    observacion:string;
    estado1:number; 
    estado2:number; 
    estado3:number;
    fecha_peticion:string;
    nota_pendiente:string;
    nota_prorroga:string;
    constancia_ex:string;
    acta_ex:string;
    fecha_presentacion_tesis:string;
    publicar:number;
    abstract:string;
    estado4:number;
    estado5:number;
    estado6:number;
    estado7:number;
    codigo_postal1:number;
    codigo_postal2:number;
    avance_general:number;
    reunion:number,
}